AWSTemplateFormatVersion: '2010-09-09'
Description: Serverless Deployment for Minerva

Transform:
    - AWS::Serverless-2016-10-31

Parameters:
    GoogleAccountClient:
        Type: String
    GoogleAccountSecret:
        Type: String
    GoogleAccountToken:
        Type: String
    SlackToken:
        Type: String
    DeployEnvironment:
        Type: String
        Default: development
        AllowedValues:
            - development
            - production

Globals:
    Api:
        OpenApiVersion: 3.0.3
    Function:
        Runtime: nodejs12.x
        Environment:
            Variables:
                production_googleaccount_redirect: "https://developers.google.com/oauthplayground/"
                production_slack_token: !Ref SlackToken
                production_googleaccount_client: !Ref GoogleAccountClient
                production_googleaccount_secret: !Ref GoogleAccountSecret
                production_googleaccount_token: !Ref GoogleAccountToken

Resources:
    MinervaApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: !Ref DeployEnvironment

    SlackCommandsSync:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub "minerva-${DeployEnvironment}-slackCommandsSync"
            CodeUri: build/index
            Handler: bundle.slack_commands_sync
            MemorySize: 128
            Timeout: 100
            Policies:
                - AWSLambdaBasicExecutionRole
            Events:
                SlackEvent:
                    Type: Api
                    Properties:
                        RestApiId: !Ref MinervaApi
                        Path: /slack/commands-sync
                        Method: post
    SlackCommandsAsync:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub "minerva-${DeployEnvironment}-slackCommandsAsync"
            CodeUri: build/index
            Handler: bundle.slack_commands_async
            MemorySize: 128
            Timeout: 100
            Policies:
                - AWSLambdaBasicExecutionRole
            Events:
                SlackEvent:
                    Type: Api
                    Properties:
                        RestApiId: !Ref MinervaApi
                        Path: /slack/commands-async
                        Method: post

    InteractivitySync:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub "minerva-${DeployEnvironment}-interactivitySync"
            CodeUri: build/index
            Handler: bundle.interactivity_sync
            MemorySize: 128
            Timeout: 100
            Policies:
                - AWSLambdaBasicExecutionRole
            Events:
                SlackEvent:
                    Type: Api
                    Properties:
                        RestApiId: !Ref MinervaApi
                        Path: /slack/interactivity-sync
                        Method: post
    InteractivityAsync:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub "minerva-${DeployEnvironment}-interactivityAsync"
            CodeUri: build/index
            Handler: bundle.interactivity_async
            MemorySize: 128
            Timeout: 100
            Policies:
                - AWSLambdaBasicExecutionRole
            Events:
                SlackEvent:
                    Type: Api
                    Properties:
                        RestApiId: !Ref MinervaApi
                        Path: /slack/interactivity-async
                        Method: post
    Scheduled:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub "minerva-${DeployEnvironment}-scheduled"
            CodeUri: build/index
            Handler: bundle.scheduled
            MemorySize: 128
            Timeout: 100
            Policies:
                - AWSLambdaBasicExecutionRole
            Events:
                SlackEvent:
                    Type: Api
                    Properties:
                        RestApiId: !Ref MinervaApi
                        Path: /slack/scheduled
                        Method: post
