AWSTemplateFormatVersion: 2010-09-09
Description: >-
    minerva

Transform:
    - AWS::Serverless-2016-10-31

Resources:
    slackCommandsSynchronous:
        Type: AWS::Serverless::Function
        Properties:
            AutoPublishAlias: development
            Handler: src/index.slack_commands_sync
            Runtime: nodejs12.x
            MemorySize: 128
            Timeout: 100
            Description: Minerva slack commands synchronous tasks
            Policies:
                - AWSLambdaBasicExecutionRole
            CodeUri: deploy

    slackCommandsAsynchronous:
        Type: AWS::Serverless::Function
        Properties:
            AutoPublishAlias: development
            Handler: src/index.slack_commands_async
            Runtime: nodejs12.x
            MemorySize: 128
            Timeout: 100
            Description: Minerva slack commands asychronous tasks
            Policies:
                - AWSLambdaBasicExecutionRole
            CodeUri: deploy

    interactivity:
        Type: AWS::Serverless::Function
        Properties:
            AutoPublishAlias: development
            Handler: src/index.interactivity
            Runtime: nodejs12.x
            MemorySize: 128
            Timeout: 100
            Description: Minerva interactivity
            Policies:
                - AWSLambdaBasicExecutionRole
            CodeUri: deploy

    scheduled:
        Type: AWS::Serverless::Function
        Properties:
            AutoPublishAlias: development
            Handler: src/index.scheduled
            Runtime: nodejs12.x
            MemorySize: 128
            Timeout: 100
            Description: Minerva scheduled events
            Policies:
                - AWSLambdaBasicExecutionRole
            CodeUri: deploy
