version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "minerva"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1blzyhgefv6n2"
s3_prefix = "minerva"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
