AWSTemplateFormatVersion: 2010-09-09
Description: minerva

Transform:
    - AWS::Serverless-2016-10-31

Parameters:
    GoogleAccountClient:
        Type: String
    GoogleAccountSecret:
        Type: String
    GoogleAccountToken:
        Type: String
    SlackToken:
        Type: String

Globals:
    Function:
        Runtime: nodejs12.x
        Environment:
            Variables:
                production_googleaccount_redirect: "https://developers.google.com/oauthplayground/"
                production_slack_token:
                    Ref: SlackToken
                production_googleaccount_client:
                    Ref: GoogleAccountClient
                production_googleaccount_secret:
                    Ref: GoogleAccountSecret
                production_googleaccount_token:
                    Ref: GoogleAccountToken

Resources:
    slackCommandsSync:
        Type: AWS::Serverless::Function
        Properties:
            Handler: src/index.slack_commands_sync
            MemorySize: 128
            Timeout: 100
            Description: Minerva slack commands synchronous tasks
            Policies:
                - AWSLambdaBasicExecutionRole

    slackCommandsAsync:
        Type: AWS::Serverless::Function
        Properties:
            Handler: src/index.slack_commands_async
            MemorySize: 128
            Timeout: 100
            Description: Minerva slack commands asychronous tasks
            Policies:
                - AWSLambdaBasicExecutionRole

    interactivitySync:
        Type: AWS::Serverless::Function
        Properties:
            Handler: src/index.interactivity_sync
            MemorySize: 128
            Timeout: 100
            Description: Minerva interactivity
            Policies:
                - AWSLambdaBasicExecutionRole

    interactivityAsync:
        Type: AWS::Serverless::Function
        Properties:
            Handler: src/index.interactivity_async
            MemorySize: 128
            Timeout: 100
            Description: Minerva interactivity
            Policies:
                - AWSLambdaBasicExecutionRole

    scheduled:
        Type: AWS::Serverless::Function
        Properties:
            Handler: src/index.scheduled
            MemorySize: 128
            Timeout: 100
            Description: Minerva scheduled events
            Policies:
                - AWSLambdaBasicExecutionRole
