name: Deploy to AWS (Production)

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
            node-version: 16.x  
      - name: npm install
        run: npm install
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: EST
      - name: Run unit tests
        run: npm run test
        working-directory: ../minerva/            
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Deploy with CDK Deploy
        shell: bash
        env:
          googleaccount_client: ${{ secrets.GOOGLE_ACCOUNT_CLIENT }}
          googleaccount_secret: ${{ secrets.GOOGLE_ACCOUNT_SECRET }}
          googleaccount_token: ${{ secrets.GOOGLE_ACCOUNT_TOKEN }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
        run: npx cdk deploy --require-approval never minerva-prod
