name: Deploy to AWS

on:
  push:
    branches: ["aws-deployment"]
  # workflow_run:
  #   workflows: ["Unit Test"]
  #   branches: ["master"]
  #   types: ["completed"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./deploy
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Set up AWS SAM CLI
        uses: aws-actions/setup-sam@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Deploy with SAM CLI
        shell: bash
        env:
          GOOGLE_ACCOUNT_CLIENT: ${{ secrets.GOOGLE_ACCOUNT_CLIENT }}
          GOOGLE_ACCOUNT_SECRET: ${{ secrets.GOOGLE_ACCOUNT_SECRET }}
          GOOGLE_ACCOUNT_TOKEN: ${{ secrets.GOOGLE_ACCOUNT_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: >-
          sam deploy --template production_template.yml
            --no-confirm-changeset
            --config-env production
            --parameter-overrides
              "GoogleAccountClient=$GOOGLE_ACCOUNT_CLIENT"
              "GoogleAccountSecret=$GOOGLE_ACCOUNT_SECRET"
              "GoogleAccountToken=$GOOGLE_ACCOUNT_TOKEN"
              "SlackToken=$SLACK_TOKEN"
