name: Unit Test

on: [push]

jobs:
    test:
        name: Run unit tests
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Setup timezone
              uses: zcong1993/setup-timezone@v1.1.1
              with:
                timezone: EST
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - run: npm install
              working-directory: ../minerva/
            - run: npm test
              working-directory: ../minerva/
